---
- name: update grub config
  ansible.builtin.command: "{{ __grub_mkconfig_command }} -o '{{ __grub_generated_config_file }}'"
  register: grub_update_result
  failed_when: grub_update_result.rc != 0
  changed_when: true
  when: ansible_virtualization_type != "docker"
