---
- name: prepare Debian Distributions
  hosts: debian
  gather_facts: false
  tasks:
    - name: update package cache
      ansible.builtin.raw: apt-get update
    - name: ensure Python is installed
      ansible.builtin.raw: apt-get install -y python3

- name: prepare RedHat Distributions
  hosts: redhat
  gather_facts: false
  tasks:
    - name: ensure Python is installed
      ansible.builtin.raw: yum install -y python36
